apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ pluck .Values.global.env .Values.app.api.grpc_port | first | default .Values.app.api.grpc_port._default }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}