// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  entities

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( MnemonicWallet ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* MnemonicWallet ) UnmarshalJSON([]byte) error { return nil }
func ( MnemonicWallet ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* MnemonicWallet ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_MnemonicWallet *MnemonicWallet
